export const skills = [
  "HTML5",
  "CSS",
  "JavaScript",
  "Redux",
  "NextJs",
  "ReactJs",
  "Typescript",
  "Testing and Debugging",
  "Browser developer tools",
  "Responsive Design",
  "Git & Github",
  "SQL",
  "Nodejs (Express)",
];
