export const projects = [
  {
    id: 102,
    name: "Fermin Guerrero's Website",
    type: "Personal website",
    client: "Fermin Guerrero",
    url: "https://ferminguerrero.com/",
    code: "https://github.com/lalidiaz/fermin-guerrero-website",
    stack: ["Nextjs", "Reactjs", "SCSS"],
  },

  {
    id: 103,
    name: "Saturnina Pizza App",
    type: "Practice skills",
    url: "https://pizza-typescript.web.app/",
    code: "https://github.com/lalidiaz/pizza-typescript-react",
    stack: ["Reactjs", "Context API", "Typescript"],
  },
  {
    id: 103,
    name: "Task manager app",
    type: "Practice skills",
    url: "https://pizza-typescript.web.app/",
    code: "https://github.com/lalidiaz/task-manager-typescript-react",
    stack: ["Reactjs", "Context API", "Typescript"],
  },
  {
    id: 304,
    name: "Change colors",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/ChangeColor-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 306,
    name: "Recipe app",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Recipe-ReactJc",
    stack: ["Reactjs"],
  },
  {
    id: 342,
    name: "Tours app",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/tours-project-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 343,
    name: "Accordion",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/accordion-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 344,
    name: "Food Menu",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/food-menu-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 345,
    name: "Tabs Menu",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/dev-portfolio-tabs-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 346,
    name: "Slider",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/slider-reactJs",
    stack: ["Reactjs"],
  },
  {
    id: 347,
    name: "Color Generator",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/colors-generator-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 348,
    name: "Grocery App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/grocery-app-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 349,
    name: "Paragraphs Generator",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/paragraph-generator-ReactJs",
    stack: ["Reactjs"],
  },

  {
    id: 350,
    name: "Reviews slider",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/reviews-project-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 351,
    name: "Birthday App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/birthday-app-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 352,
    name: "Navbar",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/navbar-reactjs",
    stack: ["Reactjs"],
  },
  {
    id: 354,
    name: "Sidebar (Context API)",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/sidebar-useContext-and-ContextAPI",
    stack: ["Reactjs"],
  },
  {
    id: 355,
    name: "Submenu (Context API)",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/submenu-useContext-Reactjs",
    stack: ["Reactjs"],
  },

  {
    id: 306,
    name: "Tigram app (Instagram version)",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Tigram-App",
    stack: ["Reactjs"],
  },
  {
    id: 340,
    name: "Animate website",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/perle-fine",
    stack: ["Reactjs", "Framer Motion"],
  },

  {
    id: 356,
    name: "Checkout cart",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/cart-usecontext-usereducer-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 357,
    name: "E-commerce",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/e-commerce-ReactJs-Typescript",
    stack: ["Reactjs", "Typescript"],
  },
  {
    id: 358,
    name: "Social Media App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/dev-socialmedia-nextjs",
    stack: ["Nextjs"],
  },
  {
    id: 307,
    name: "Counter",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Counter-Redux",
    stack: ["Reactjs", "Redux"],
  },
  {
    id: 309,
    name: "Login example app",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/redux-example",
    stack: ["Reactjs", "Redux"],
  },
  {
    id: 310,
    name: "Crypto Tracker App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/cryptotracker-React-Native",
    stack: ["Reactjs Native"],
  },
  {
    id: 311,
    name: "Spotify Clone - Typescript",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Spotify-Clone-React-Native",
    stack: ["Reactjs Native"],
  },
  {
    id: 300,
    name: "Weather App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Weather-Fetch",
    stack: ["Javascript Vanilla"],
  },
  {
    id: 3032,
    name: "Word Association Game",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/word-association-javascript-vanilla",
    stack: ["Javascript Vanilla"],
  },

  {
    id: 301,
    name: "My moms artist website",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Ely-AguileraArtWeb",
    stack: ["Javascript Vanilla"],
  },
  {
    id: 490,
    name: "Random Cat",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/RANDOM-CAT",
    stack: ["Javascript Vanilla"],
  },
  {
    id: 302,
    name: "3D Cards",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Bali-Experience-3DCards",
    stack: ["CSS"],
  },
  {
    id: 303,
    name: "Parallax Architecture website",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/La-Muralla-Roja",
    stack: ["CSS"],
  },
];
