export const projects = [
  {
    id: 1,
    name: "Fermin Guerrero's Website",
    type: "Personal website",
    client: "Fermin Guerrero",
    url: "https://ferminguerrero.com/",
    code: "https://github.com/lalidiaz/fermin-guerrero-website",
    stack: ["Nextjs", "Reactjs", "SCSS"],
  },

  {
    id: 2,
    name: "Saturnina Pizza App",
    type: "Practice skills",
    url: "https://pizza-typescript.web.app/",
    code: "https://github.com/lalidiaz/pizza-typescript-react",
    stack: ["Reactjs", "Context API", "Typescript"],
  },
  {
    id: 3,
    name: "Task manager app",
    type: "Practice skills",
    url: "https://task-manager-typescript-react.vercel.app/",
    code: "https://github.com/lalidiaz/task-manager-typescript-react",
    stack: ["Reactjs", "Context API", "Typescript"],
  },

  {
    id: 8,
    name: "Food Menu",
    type: "Practice skills",
    url: "https://food-menu-react-js.vercel.app/",
    code: "https://github.com/lalidiaz/food-menu-ReactJs",
    stack: ["Reactjs"],
  },

  {
    id: 7,
    name: "Accordion",
    type: "Practice skills",
    url: "https://accordion-react-js.vercel.app/",
    code: "https://github.com/lalidiaz/accordion-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 4,
    name: "Change colors",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/ChangeColor-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 21,
    name: "Checkout cart",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/cart-usecontext-usereducer-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 6,
    name: "Tours app",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/tours-project-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 5,
    name: "Recipe app",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Recipe-ReactJc",
    stack: ["Reactjs"],
  },
  {
    id: 22,
    name: "E-commerce",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/e-commerce-ReactJs-Typescript",
    stack: ["Reactjs", "Typescript"],
  },
  {
    id: 9,
    name: "Tabs Menu",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/dev-portfolio-tabs-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 10,
    name: "Slider",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/slider-reactJs",
    stack: ["Reactjs"],
  },
  {
    id: 11,
    name: "Color Generator",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/colors-generator-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 12,
    name: "Grocery App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/grocery-app-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 29,
    name: "Word Association Game",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/word-association-javascript-vanilla",
    stack: ["Javascript Vanilla"],
  },
  {
    id: 13,
    name: "Paragraphs Generator",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/paragraph-generator-ReactJs",
    stack: ["Reactjs"],
  },

  {
    id: 14,
    name: "Reviews slider",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/reviews-project-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 15,
    name: "Birthday App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/birthday-app-ReactJs",
    stack: ["Reactjs"],
  },
  {
    id: 16,
    name: "Navbar",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/navbar-reactjs",
    stack: ["Reactjs"],
  },
  {
    id: 17,
    name: "Sidebar (Context API)",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/sidebar-useContext-and-ContextAPI",
    stack: ["Reactjs"],
  },
  {
    id: 18,
    name: "Submenu (Context API)",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/submenu-useContext-Reactjs",
    stack: ["Reactjs"],
  },

  {
    id: 19,
    name: "Tigram app (Instagram version)",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Tigram-App",
    stack: ["Reactjs"],
  },
  {
    id: 20,
    name: "Animate website",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/perle-fine",
    stack: ["Reactjs", "Framer Motion"],
  },

  {
    id: 23,
    name: "Social Media App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/dev-socialmedia-nextjs",
    stack: ["Nextjs"],
  },
  {
    id: 24,
    name: "Counter",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Counter-Redux",
    stack: ["Reactjs", "Redux"],
  },
  {
    id: 25,
    name: "Login example app",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/redux-example",
    stack: ["Reactjs", "Redux"],
  },
  {
    id: 26,
    name: "Crypto Tracker App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/cryptotracker-React-Native",
    stack: ["Reactjs Native"],
  },
  {
    id: 27,
    name: "Spotify Clone - Typescript",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Spotify-Clone-React-Native",
    stack: ["Reactjs Native"],
  },
  {
    id: 28,
    name: "Weather App",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Weather-Fetch",
    stack: ["Javascript Vanilla"],
  },

  {
    id: 30,
    name: "My moms artist website",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Ely-AguileraArtWeb",
    stack: ["Javascript Vanilla"],
  },
  {
    id: 31,
    name: "Random Cat",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/RANDOM-CAT",
    stack: ["Javascript Vanilla"],
  },
  {
    id: 32,
    name: "3D Cards",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/Bali-Experience-3DCards",
    stack: ["CSS"],
  },
  {
    id: 33,
    name: "Parallax Architecture website",
    type: "Practice skills",
    code: "https://github.com/lalidiaz/La-Muralla-Roja",
    stack: ["CSS"],
  },
];
